2020-09-21 08:17:08,741 ERROR 19252 nodejs.ClusterClientNoResponseError: client no response in 8464109ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 19252
hostname: J9MO9BU01VTBF92

2020-09-21 09:18:20,751 ERROR 14828 [-/192.168.0.174/-/16ms POST /user/add] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1"
sqlState: "22007"
index: 0
sql: "INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')"
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:18:28,184 ERROR 14828 [-/192.168.0.174/-/5ms POST /user/add] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1"
sqlState: "22007"
index: 0
sql: "INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')"
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:23:53,425 ERROR 14828 [-/192.168.0.174/-/14ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:24:23,161 ERROR 14828 [-/192.168.0.174/-/6ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:25:37,980 ERROR 14828 [-/192.168.0.174/-/19ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`, `email`) VALUES('2222', '222', '测试1', '2222')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`, `email`) VALUES('2222', '222', '测试1', '2222')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 12:49:34,991 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 2865326ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-21 13:04:35,879 ERROR 4724 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-21 23:58:06,403 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 10809872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-22 00:03:30,044 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 323079ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

